
networks:
  network_example:
    name: network_example
    driver: bridge

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb_example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  nginx-example:
    container_name: nginx-example-network
    image: nginx:latest
    networks:
      - network_example